[2023-11-30 15:10:25,121] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v04.greet scheduled__2023-11-29T00:00:00+00:00 [queued]>
[2023-11-30 15:10:25,130] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v04.greet scheduled__2023-11-29T00:00:00+00:00 [queued]>
[2023-11-30 15:10:25,131] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-11-30 15:10:25,131] {taskinstance.py:1244} INFO - Starting attempt 3 of 6
[2023-11-30 15:10:25,131] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2023-11-30 15:10:25,144] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): greet> on 2023-11-29 00:00:00+00:00
[2023-11-30 15:10:25,148] {standard_task_runner.py:52} INFO - Started process 22656 to run task
[2023-11-30 15:10:25,150] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v04', 'greet', 'scheduled__2023-11-29T00:00:00+00:00', '--job-id', '631', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpyxz543y2', '--error-file', '/tmp/tmp8x4ff4hu']
[2023-11-30 15:10:25,151] {standard_task_runner.py:77} INFO - Job 631: Subtask greet
[2023-11-30 15:10:25,200] {logging_mixin.py:109} INFO - Running <TaskInstance: our_dag_with_python_operator_v04.greet scheduled__2023-11-29T00:00:00+00:00 [running]> on host 08735726aeda
[2023-11-30 15:10:25,246] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ali
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v04
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2023-11-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-29T00:00:00+00:00
[2023-11-30 15:10:25,246] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 14, in greet
    name = ti.xcoms_pull(task_ids='get_name') # get the name from the previous task get_name()
AttributeError: 'TaskInstance' object has no attribute 'xcoms_pull'
[2023-11-30 15:10:25,257] {taskinstance.py:1282} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v04, task_id=greet, execution_date=20231129T000000, start_date=20231130T151025, end_date=20231130T151025
[2023-11-30 15:10:25,272] {standard_task_runner.py:92} ERROR - Failed to execute job 631 for task greet
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 14, in greet
    name = ti.xcoms_pull(task_ids='get_name') # get the name from the previous task get_name()
AttributeError: 'TaskInstance' object has no attribute 'xcoms_pull'
[2023-11-30 15:10:25,285] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-11-30 15:10:25,311] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04 11:08:01,891] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v04.greet scheduled__2023-11-29T00:00:00+00:00 [queued]>
[2023-12-04 11:08:01,900] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v04.greet scheduled__2023-11-29T00:00:00+00:00 [queued]>
[2023-12-04 11:08:01,900] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-12-04 11:08:01,900] {taskinstance.py:1244} INFO - Starting attempt 3 of 6
[2023-12-04 11:08:01,900] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2023-12-04 11:08:01,911] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): greet> on 2023-11-29 00:00:00+00:00
[2023-12-04 11:08:01,913] {standard_task_runner.py:52} INFO - Started process 939 to run task
[2023-12-04 11:08:01,916] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v04', 'greet', 'scheduled__2023-11-29T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpfdbnjrk6', '--error-file', '/tmp/tmpja960ero']
[2023-12-04 11:08:01,916] {standard_task_runner.py:77} INFO - Job 23: Subtask greet
[2023-12-04 11:08:01,951] {logging_mixin.py:109} INFO - Running <TaskInstance: our_dag_with_python_operator_v04.greet scheduled__2023-11-29T00:00:00+00:00 [running]> on host 9953e82db65e
[2023-12-04 11:08:01,992] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ali
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v04
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2023-11-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-29T00:00:00+00:00
[2023-12-04 11:08:01,998] {logging_mixin.py:109} INFO - Hello world! my name is Ali, and I am 20 years old.
[2023-12-04 11:08:01,998] {python.py:175} INFO - Done. Returned value was: None
[2023-12-04 11:08:02,010] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=our_dag_with_python_operator_v04, task_id=greet, execution_date=20231129T000000, start_date=20231204T110801, end_date=20231204T110802
[2023-12-04 11:08:02,047] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-12-04 11:08:02,073] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
