[2023-12-04 12:52:37,055] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2023-12-02T00:00:00+00:00 [queued]>
[2023-12-04 12:52:37,067] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2023-12-02T00:00:00+00:00 [queued]>
[2023-12-04 12:52:37,067] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-12-04 12:52:37,067] {taskinstance.py:1244} INFO - Starting attempt 6 of 6
[2023-12-04 12:52:37,067] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2023-12-04 12:52:37,080] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): greet> on 2023-12-02 00:00:00+00:00
[2023-12-04 12:52:37,083] {standard_task_runner.py:52} INFO - Started process 4277 to run task
[2023-12-04 12:52:37,086] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v05', 'greet', 'scheduled__2023-12-02T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpnj0rk2sq', '--error-file', '/tmp/tmpgwazdkb9']
[2023-12-04 12:52:37,087] {standard_task_runner.py:77} INFO - Job 62: Subtask greet
[2023-12-04 12:52:37,132] {logging_mixin.py:109} INFO - Running <TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2023-12-02T00:00:00+00:00 [running]> on host 9953e82db65e
[2023-12-04 12:52:37,180] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ali
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v05
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2023-12-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-02T00:00:00+00:00
[2023-12-04 12:52:37,181] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 1 required positional argument: 'age'
[2023-12-04 12:52:37,191] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=our_dag_with_python_operator_v05, task_id=greet, execution_date=20231202T000000, start_date=20231204T125237, end_date=20231204T125237
[2023-12-04 12:52:37,203] {standard_task_runner.py:92} ERROR - Failed to execute job 62 for task greet
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 1 required positional argument: 'age'
[2023-12-04 12:52:37,218] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-12-04 12:52:37,242] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
